source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'PerchBroadcastExample', :exclusive => true do
  pod "PerchBroadcast", :path => "../"
end

target 'PerchBroadcastExampleTests', :exclusive => true do
  pod "PerchBroadcast", :path => "../"
  pod 'URLMock', '~> 1.3.1'
  
end
