source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'Broadcast', :exclusive => true do
  pod "PerchBroadcast", :path => "../"
end

target 'BroadcastMock', :exclusive => true do
  pod "PerchBroadcast", :path => "../"
end

target 'PerchBroadcastTests', :exclusive => true do
  pod "PerchBroadcast", :path => "../"
  pod 'URLMock', '~> 1.3.1'
end
